friends/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :tasks
  resources :friends
  #get 'home/index'
  get 'home/about'
 # root 'home#index'
  root 'friends#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

friends/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

friends/app/models/friend.rb
class Friend < ApplicationRecord
 belongs_to :user
end

friends/app/models/task.rb
class Task < ApplicationRecord
end

friends/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

friends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

friends/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

friends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about

  end

end

friends/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.fetch(:task, {})
    end
end

friends/app/helpers/application_helper.rb
module ApplicationHelper
end

friends/app/helpers/friends_helper.rb
module FriendsHelper
end

friends/app/helpers/home_helper.rb
module HomeHelper
end

friends/app/helpers/tasks_helper.rb
module TasksHelper
end

friends/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"Johnson" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Darko"  %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", class:"form-control", placeholder:"john@gmail.com"  %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"021354558"  %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"twitter@joohn1"  %>
  </div>
  <div class="field form-group">

    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>


<br/>
  <div class="action">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

friends/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

friends/app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>

<br/>
<div>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>
</div>

friends/app/views/friends/index.html.erb
<% if user_signed_in? %>

<h1>Friends List</h1>
<table class="table table-striped table-bordered table-hover">
  <thead >
    <tr class="bg-secondary">
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

<div id="friends">
  <% @friends.each do |friend| %>
  <% if friend.user == current_user %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to "Show friend", friend, class: "btn btn-outline-success btn-sm" %></td>
        <td><%= link_to "Edit", edit_friend_path(friend), class: "btn btn-outline-warning btn-sm" %></td>
        <td><%= button_to 'Delete', friend, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger mx-4" %></td>
      </tr>
      <% end %>
       <% end %>
</div>
  </tbody>
  <table>
  <br>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>
<% else %>

<h2>Hello Visitor👋</h2>
<div class="card">
 <div class="card-header">
<h3> I'm Johnson Darko,a Full Stack Web Developer😎</h3>
 <div class="card-header">



		<p>You can sign up to enjoy the features of this website even though it is not yet complete.
		</p>

</div>


<% end %>

friends/app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"btn btn-dark"  %>
</div>

friends/app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  |
    <%= @friend.phone %>  |
    <%= @friend.twitter %>

  </p>
  <br/>

  <br/>

<%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>



</div>

friends/app/views/home/_footer.html.erb
<div class="footer mt-4 text-center">
  <div class="footer-copyright">
    Design by JOHNSON  <i class="fas fa-heart"></i> DARKO
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

</div>

friends/app/views/home/_header.html.erb
    <div class="navbar bg-light border-bottom">
      <div class="container">
      <a class="navbar-brand" href="#">
       <img src="https://scontent-dus1-1.xx.fbcdn.net/v/t1.6435-1/51288995_1218000288348043_804808650009870336_n.jpg?stp=dst-jpg_p320x320&_nc_cat=109&ccb=1-7&_nc_sid=7206a8&_nc_ohc=jd1VP-LRibIAX8_qsJS&tn=rTxgKrhWPRlptM74&_nc_ht=scontent-dus1-1.xx&oh=00_AT_qIRAKsY6ybgGlY3PK4Hrc_7mDK2jO9Dw04OCz05XJ-A&oe=63186D04" width="70" height="70"  alt="" class="rounded-circle">

          <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
             <%= link_to 'Friends', friends_path, class: "navbar-brand", class: "btn btn-sm" %>

              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">


                <% if user_signed_in?%>


                <% link_to 'Home', root_path, class: "nav-link", class: "btn btn-sm" %>
                 <% link_to 'About', home_about_path, class: "nav-link", class: "btn btn-sm" %>
                  <%= link_to 'Add Friend', new_friend_path, class: "nav-link", class: "btn btn-sm" %>
                    <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link", class: "btn btn-sm" %>
                    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link", class: "btn btn-sm" %>

                      <% else %>
                      <%= link_to 'Sign In',  new_user_session_path, class: "nav-link", class: "btn btn-sm" %>
                     <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link", class: "btn btn-sm" %>
                    <% end %>


                </div>
              </div>
            </div>
          </nav>


      </div>
    </div>

friends/app/views/home/about.html.erb
<h1 class="text-center">About Page</h1>

friends/app/views/home/index.html.erb
<h1 class="text-center">Home Page</h1>

friends/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
   <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

  <%= render 'home/header' %>
  <div class="container">

 <br>
  <%= render "devise/shared/flash" %>
    <%= yield %>
  </div>
  <div class="container">
  <%= render 'home/footer' %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </body>
</html>

friends/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

friends/app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
</div>

friends/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

friends/app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

friends/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

friends/app/views/tasks/show.html.erb
<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>